spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mediapulse
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop

media-pulse:
  plex:
    base-url: https://plex.marcal.dev
    token: ofjEGkUBjbyLF9DWBgkS
    import:
      enabled: true
      page-size: 200
      schedule-cron: "0 0 * * * *"
      run-on-startup: true
  storage:
    covers-path: "./covers"

