spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mediapulse
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop

media-pulse:
  plex:
    base-url: http://localhost:32400
    token: "YOUR_DEV_TOKEN"
    import:
      enabled: true
      page-size: 200
      schedule-cron: "0 0 * * * *"
      run-on-startup: false
  storage:
    covers-path: "."

