spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mediapulse
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop

media-pulse:
  pipeline:
    enabled: true
    schedule-cron: "0 0 * * * *"
    run-on-startup: false
  plex:
    base-url: http://localhost:32400
    token: "YOUR_DEV_TOKEN"
  storage:
    covers-path: "."

